config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

  resources :posts

  resources :profile_settings, only: [:index] do
    collection do
      get :followers
      get :followings
    end
  end

  resources :relationships, only: %i[create destroy]

  get "users/search"
  devise_for :users, controllers: { registrations: "registrations" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_attachments

  validates_presence_of :content

  accepts_nested_attributes_for :post_attachments
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :set_full_name

  validates_presence_of :first_name, :last_name

  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def set_full_name
    self.full_name = "#{first_name} #{last_name}"
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :miniprofiler if Rails.env.development? || Rails.env.test?

  private

  def authorize
    redirect_to new_user_session_path unless user_signed_in?
  end

  def miniprofiler
    Rack::MiniProfiler.authorize_request
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize
  before_action :find_post, only: %i[edit update destroy]

  def index
    show_posts_of = [current_user.id] + current_user.following.pluck(:id)
    @posts = Post.includes(:user).where(user_id: show_posts_of).order(created_at: :desc)

    @post = Post.new
  end

  def new; end

  def create
    @post = Post.new(post_params)

    head :ok unless @post.save
  end

  def edit; end

  def update
    head :ok unless @post.update(post_params)
  end

  def destroy
    @post.destroy if @post.present?
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, post_attachments_attributes: [:id, :post_id, :avatar])
  end

  def find_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/profile_settings_controller.rb
class ProfileSettingsController < ApplicationController
  before_action :authorize

  def index
    @user = User.find_by(id: params[:user_id])
    @posts = @user.posts

    @post = Post.new
  end

  def followers
    @user = User.find_by(id: params[:user_id])
    @followers_list = @user.followers
  end

  def followings
    @user = User.find_by(id: params[:user_id])
    @followings_list = @user.following
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authorize

  def create
    @user = User.find_by(id: params[:followed_id])
    @relationship = current_user.active_relationships.find_by(followed_id: params[:followed_id])
    current_user.follow(@user) if @user.present? && !@relationship.present?
  end

  def destroy
    @user = User.find_by(id: params[:id])
    current_user.unfollow(@user) if @user.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize

  def search
    @users = User.where("full_name LIKE ?", "%#{params[:q]}%").limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_settings_helper.rb
module ProfileSettingsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instapost</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default" style="background: #354670;margin-bottom: 0px;">
      <div class="container-fluid">
        <div class="navbar-header" style="border-right: 1px solid #fff;">
          <span class="navbar-brand" style="color:#fff;font-size: 20px;">InstaPost <span style="font-size: 10px;">by Huzaifa Saifuddin</span></span>
        </div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to("Home", posts_path, style: "color:#fff;") %></li>
            <li><%= link_to("Profile", profile_settings_path(user_id: current_user.id.to_s), style: "color:#fff;") %></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" id="search-users" class="form-control" placeholder="Search Friends">
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right" style="border-left: 1px solid #fff;">
            <li><%= link_to("Logout", destroy_user_session_path, method: :delete, style: "color:#fff;") %></li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

<script type="text/javascript">
  function search_users(){
    $("#search-users").autocomplete({
      minLength: 3,
      source: function(request, response){
        $.ajax({
          dataType: "json",
          type : 'get',
          url: '/users/search',
          data: {q: request.term.replace(/[^\w\s]/gi, ''), remote: "true"},
          success: function(data) {
            response(data);
          }
        });
      },
      select: function( event, ui ){
        // $.ajax({
        //   type: "GET",
        //   dataType: "html",
        //   url: "/profile_settings?user_id="+ ui.item["id"],
        // })
      },
      create: function () {
        $(this).data('ui-autocomplete')._renderItem = function (ul, user) {          
          return $('<li class="text-center" style="font-size:16px;">')
            .append("<a href='/profile_settings?user_id=" + user.id + "'>" + user.label + "</a>")
            .appendTo(ul);
        }
      }
    });
  }

  $('#search-users').keyup(search_users);
</script>

<style type="text/css">
  .ui-menu-item-wrapper:hover, .ui-menu-item-wrapper:active {
    background: none;
    border: none;
    color: #000;
  }

  .ui-state-active, .ui-widget-content .ui-state-active, .ui-widget-header .ui-state-active, a.ui-button:active, .ui-button:active, .ui-button.ui-state-active:hover {
    background: none;
    border: none;
    color: #000; 
  }
</style>

app/views/posts/_create.html.erb
<div class="row" id="post_<%= @post.id %>" style="margin-top: 10px;">
  <%= render partial: "show.html.erb" %>
</div>
<hr id="hr-post-<%= @post.id %>">

app/views/posts/_edit.html.erb
<div class="col-md-12">
  <%= form_for @post, remote: true, style: "width:100%;" do |f| %>
    <div class="col-md-12">
      <strong>Edit Post</strong>
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.text_area :content, class: "form-control", placeholder: "Hey #{current_user.first_name}! What's on your mind?" %>
    </div>
    <div class="col-md-6 edit-content-error" style="margin-top: 10px;"></div>
    <div class="col-md-6 text-right" style="margin-top: 10px;">
      <%= f.submit "Update", class: "btn btn-primary", onclick: 'edit_post_form()' %>
      <button class="btn btn-default btn-close">Close</button>
    </div>
  <% end %>
</div>

app/views/posts/_new.html.erb
<%= form_for @post, remote: true, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.text_area :content, class: "form-control", placeholder: "Hey #{current_user.first_name}! What's on your mind?" %>
    </div>
    <div class="col-md-12">
      <%= f.file_field :avatar, multiple: true, name: 'post[post_attachments_attributes][][avatar]' %>
    </div>
    <div class="col-md-6 content-error" style="margin-top: 10px;"></div>
    <div class="col-md-6 text-right" style="margin-top: 10px;">
      <%= f.submit "Click to Post", class: "btn btn-primary", onclick: "post_form()" %>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  function post_form(){
    $("#new_post").validate({
      rules: {
        "post[content]": {
          required: true,
        }
      },
      messages: {
        "post[content]": {
          required: "Seems like you have nothing in mind.",
        }
      },
      errorPlacement: function (error, element) {
        var name = $(element).attr('name')
        if(name == 'post[content]') {
          $(".content-error").append(error)
        }
      }
    });
  }
  post_form()
</script>

app/views/posts/_show.html.erb
<div class="col-md-9">
  <strong style="font-size: 16px;"><%= @post.content %></strong>
</div>
<div class="col-md-3 text-right">
  <%= link_to('Edit', edit_post_path(@post), remote: true, class: "edit_post#{@post.id}", style: "font-size:12px;") %> | <%= link_to('Delete', post_path(@post), method: :delete, remote: true, class: "delete_post#{@post.id}", style: "font-size:12px;") %>
</div>
<div class="col-md-6">
  <span style="font-size:12px;"><%= @post.user.full_name %></span>
</div>
<div class="col-md-6 text-right">
  <span style="font-size:12px;"><%= @post.created_at.strftime("%I:%M %p, %d/%m/%Y") %></span>
</div>
<div class="col-md-12">
  <div class="row">
    <% @post.post_attachments.each do |attachment| %>
      <div class="col-md-2" style="margin: 5px;">
        <%= image_tag attachment.avatar_url(:thumb) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/create.js.erb
if($("#all-posts").length > 0){
  $("#all-posts").prepend("<%= escape_javascript(render partial: 'create.html.erb') %>")
} else if($("#my-posts").length > 0){
  $("#my-posts").prepend("<%= escape_javascript(render partial: 'create.html.erb') %>")
}

$("#post_content").val("")

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").remove()
$("#hr-post-<%= @post.id %>").remove()

app/views/posts/edit.js.erb
$("#post_<%= @post.id %>").html("<%= escape_javascript(render partial: 'edit.html.erb') %>")

$(".btn-close").on('click', function(e){
  e.preventDefault();
  $("#post_<%= @post.id %>").html("<%= escape_javascript(render 'show.html.erb') %>");
})

function edit_post_form(){
  $("#edit_post_<%= @post.id %>").validate({
    rules: {
      "post[content]": {
        required: true,
      }
    },
    messages: {
      "post[content]": {
        required: "Cant leave it empty.",
      }
    },
    errorPlacement: function (error, element) {
      var name = $(element).attr('name')
      if(name == 'post[content]') {
        $(".edit-content-error").append(error)
      }
    }
  });
}
edit_post_form()

app/views/posts/index.html.erb
<div class="row" style="margin-top:10px;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <!-- Post Form -->
    <div id="new-post">
      <%= render partial: "new.html.erb" %>
    </div>
    <hr/>
    <!-- All Post -->
    <div id="all-posts">
      <% @posts.each do |post| %>
        <div class="row" id="post_<%= post.id %>" style="margin-top: 10px;">
          <div class="col-md-9">
            <strong style="font-size: 16px;"><%= post.content %></strong>
          </div>
          <div class="col-md-3 text-right">
            <% if post.user_id == @current_user.id %>
              <%= link_to('Edit', edit_post_path(post), remote: true, class: "edit_post#{post.id}", style: "font-size:12px;") %> | <%= link_to('Delete', post_path(post), method: :delete, remote: true, class: "delete_post#{post.id}", style: "font-size:12px;") %>
            <% end %>
          </div>
          <div class="col-md-6">
            <span style="font-size:12px;"><%= post.user.full_name %></span>
          </div>
          <div class="col-md-6 text-right">
            <span style="font-size:12px;"><%= post.created_at.strftime("%I:%M %p, %d/%m/%Y") %></span>
          </div>
          <div class="col-md-12">
            <div class="row">
              <% post.post_attachments.each do |attachment| %>
                <div class="col-md-2" style="margin: 5px;">
                  <%= image_tag attachment.avatar_url(:thumb) %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <hr id="hr-post-<%= post.id %>" />
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
$("#new-post").html("<%= render partial: 'new.html.erb' %>")

app/views/posts/update.js.erb
$("#post_<%= @post.id %>").html("<%= escape_javascript(render partial: 'show.html.erb') %>")

app/views/profile_settings/_profile.html.erb
<div class="row">
  <% if @user.id == @current_user.id %>
    <div class="col-md-12 text-center">
      <h3><%= @user.full_name %><br/><span style='font-size: 12px;'><%= @user.email %></span></h3>
    </div>
  <% else %>
    <div class="col-md-6">
      <h3><%= @user.full_name %><br/><span style='font-size: 12px;'><%= @user.email %></span></h3>
    </div>
    <div class="col-md-6 text-right">
      <% if @current_user.following?(@user) %>
        <%= link_to('Unfollow', relationship_path(id: @user.id), method: :delete, remote: true, class: 'btn btn-danger', style: "font-size:12px;margin-top:18%;") %>
      <% else %>
        <%= link_to('Follow', relationships_path(followed_id: @user.id), method: :post, remote: true, class: 'btn btn-primary', style: "font-size:12px;margin-top:18%;") %>
      <% end %>
    </div>
  <% end %>
</div>
<hr/>
<div class="row text-center">
  <div class="col-md-6">
    <% if @user.followers.count > 0 %>
      <h3><%= link_to followers_profile_settings_path(user_id: @user.id), class: 'followers-list-link' do %><%= @user.followers.count %> Followers<% end %></h3>
    <% else %>
      <h3>No Followers</h3>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if @user.following.count > 0 %>
      <h3><%= link_to followings_profile_settings_path(user_id: @user.id), class: 'followings-list-link' do %><%= @user.following.count %> Following<% end %></h3>
    <% else %>
      <h3>No Followings</h3>
    <% end %>
  </div>
</div>

app/views/profile_settings/_show.html.erb
<div id='user-profile'>
  <%= render partial: "profile.html.erb" %>
</div>
<hr/>
<% if @user.id == @current_user.id %>      
  <div id="new-post">
    <%= render partial: "posts/new.html.erb" %>
  </div>
  <hr/>
<% end %>
<div id="my-posts">
  <% @posts.each do |post| %>
    <div class="row" id="post_<%= post.id %>" style="margin-top: 10px;">
      <div class="col-md-9">
        <strong style="font-size: 16px;"><%= post.content %></strong>
      </div>
      <div class="col-md-3 text-right">
        <% if post.user_id == @current_user.id %>
          <%= link_to('Edit', edit_post_path(post), remote: true, style: "font-size:12px;") %> | <%= link_to('Delete', post_path(post), method: :delete, style: "font-size:12px;") %>
        <% end %>
      </div>
      <div class="col-md-6">
        <span style="font-size:12px;"><%= post.user.full_name %></span>
      </div>
      <div class="col-md-6 text-right">
        <span style="font-size:12px;"><%= post.created_at.strftime("%I:%M %p, %d/%m/%Y") %></span>
      </div>
      <div class="col-md-12">
        <div class="row">
          <% post.post_attachments.each do |attachment| %>
            <div class="col-md-2" style="margin: 5px;">
              <%= image_tag attachment.avatar_url(:thumb) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <hr/>
  <% end %>
  <% if @posts.count <= 0 %>
    <div class="row text-center">
      <div class="col-md-12">
        <strong style="font-size: 16px;">No Posts Yet</strong>
      </div>
    </div>
  <% end %>
</div>

<style type="text/css">
  .followers-list-link:hover, .followings-list-link:hover {
    text-decoration: none;
  }
</style>

app/views/profile_settings/followers.html.erb
<input type="hidden" class="this-user-id" value="<%= @user.id %>">
<div class="row" style="margin-top:10px;">
  <div class="col-md-3"></div>
  <div class="col-md-6" id="users-followers">
    <div class="row">
      <div class="col-md-12 text-center">
        <% if @current_user.id == @user.id %>
          <h3>PEOPLE WHO FOLLOW YOU</h3>
        <% else %>
          <h3>PEOPLE WHO FOLLOW&emsp;<%= link_to profile_settings_path(user_id: @user.id) do %><%= @user.full_name.to_s.upcase %><% end %></h3>
        <% end %>
      </div>
    </div>
    <hr/>
    <div id='followers-list'>
      <% @followers_list.each do |follower| %>
        <div class="row" id="user_<%= follower.id %>">
          <div class="col-md-6">
            <h3><%= follower.full_name %><br/><span style='font-size: 12px;'><%= follower.email %></span></h3>
          </div>
          <div class="col-md-6 text-right">
            <%= link_to profile_settings_path(user_id: follower.id), class: 'btn btn-info', style: "font-size:12px;margin-top:18%;" do %>View Profile<% end %>
            <% if @current_user.id != follower.id %>
              <span id='relationsip_actions_<%= follower.id %>'>
                <% if @current_user.following?(follower) %>
                  <%= link_to('Unfollow', relationship_path(id: follower.id), method: :delete, remote: true, class: 'btn btn-danger', style: "font-size:12px;margin-top:18%;") %>
                <% else %>
                  <%= link_to('Follow', relationships_path(followed_id: follower.id), method: :post, remote: true, class: 'btn btn-primary', style: "font-size:12px;margin-top:18%;") %>
                <% end %>
              </span>
            <% end %>
          </div>
        </div>
        <hr id="hr-user-<%= follower.id %>" />
      <% end %>
      <% if @followers_list.count <= 0 %>
        <div class='row'>
          <div class='col-md-12 text-center'>
            <h3>Nothing to show</h3>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profile_settings/followings.html.erb
<input type="hidden" class="this-user-id" value="<%= @user.id %>">
<div class="row" style="margin-top:10px;">
  <div class="col-md-3"></div>
  <div class="col-md-6" id="users-followings">
    <div class="row">
      <div class="col-md-12 text-center">
        <% if @current_user.id == @user.id %>
          <h3>PEOPLE YOU FOLLOW</h3>
        <% else %>
          <h3>PEOPLE&emsp;<%= link_to profile_settings_path(user_id: @user.id) do %><%= @user.full_name.to_s.upcase %><% end %>&emsp;FOLLOWS</h3>
        <% end %>
      </div>
    </div>
    <hr/>
    <div id='followings-list'>
      <% @followings_list.each do |following| %>
        <div class="row" id="user_<%= following.id %>">
          <div class="col-md-6">
            <h3><%= following.full_name %><br/><span style='font-size: 12px;'><%= following.email %></span></h3>
          </div>
          <div class="col-md-6 text-right">
            <%= link_to profile_settings_path(user_id: following.id), class: 'btn btn-info', style: "font-size:12px;margin-top:18%;" do %>View Profile<% end %>
            <% if @current_user.id != following.id %>
              <span id='relationsip_actions_<%= following.id %>'>
                <% if @current_user.following?(following) %>
                  <%= link_to('Unfollow', relationship_path(id: following.id), method: :delete, remote: true, class: 'btn btn-danger', style: "font-size:12px;margin-top:18%;") %>
                <% else %>
                  <%= link_to('Follow', relationships_path(followed_id: following.id), method: :post, remote: true, class: 'btn btn-primary', style: "font-size:12px;margin-top:18%;") %>
                <% end %>
              </span>
            <% end %>
          </div>
        </div>
        <hr id="hr-user-<%= following.id %>" />
      <% end %>
      <% if @followings_list.count <= 0 %>
        <div class='row'>
          <div class='col-md-12 text-center'>
            <h3>Nothing to show</h3>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profile_settings/index.html.erb
<div class="row" style="margin-top:10px;">
  <div class="col-md-3"></div>
  <div class="col-md-6" id="users-dashboard">
    <%= render partial: 'show.html.erb' %>
  </div>
</div>

app/views/relationships/_relation_action.html.erb
<% if @current_user.following?(@user) %>
  <%= link_to('Unfollow', relationship_path(id: @user.id), method: :delete, remote: true, class: 'btn btn-danger', style: "font-size:12px;margin-top:18%;") %>
<% else %>
  <%= link_to('Follow', relationships_path(followed_id: @user.id), method: :post, remote: true, class: 'btn btn-primary', style: "font-size:12px;margin-top:18%;") %>
<% end %>

app/views/relationships/create.js.erb
if($("#users-followings").length > 0){
  $("#relationsip_actions_<%= @user.id %>").html("<%= escape_javascript(render 'relation_action.html.erb') %>")
} else if($("#users-followers").length > 0){
  $("#relationsip_actions_<%= @user.id %>").html("<%= escape_javascript(render 'relation_action.html.erb') %>")
} else if($("#users-dashboard").length > 0){
  $("#user-profile").html("<%= escape_javascript(render 'profile_settings/profile.html.erb') %>")
}

app/views/relationships/destroy.js.erb
if($("#users-followings").length > 0){
  if($(".this-user-id").val() == "<%= @current_user.id %>"){
    $("#user_<%=@user.id%>").remove()
    $("#hr-user-<%= @user.id %>").remove()
    if($("#followings-list").html().trim() == ""){
      $("#followings-list").html("<div class='row'><div class='col-md-12 text-center'><h3>Nothing to show</h3></div></div>")
    }
  } else {
    $("#relationsip_actions_<%= @user.id %>").html("<%= escape_javascript(render 'relation_action.html.erb') %>")
  }
} else if($("#users-followers").length > 0){
  $("#relationsip_actions_<%= @user.id %>").html("<%= escape_javascript(render 'relation_action.html.erb') %>")
} else if($("#users-dashboard").length > 0){
  $("#user-profile").html("<%= escape_javascript(render 'profile_settings/profile.html.erb') %>")
}